GET http://localhost:3000/usuarios

###
GET http://localhost:3000/usuarios/1

###
POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nombre": "Julio",
    "apellido": "Aguilar",
    "email": "Julio@gmail.com"
}


