GET http://localhost:3000/pokemon

###
GET http://localhost:3000/pokemon/10

###
POST http://localhost:3000/pokemon
Content-Type: application/json

{
    "pokemon":"Bulbas"
}

###
PUT  http://localhost:3000/pokemon/152
Content-Type: application/json

{
    "pokemon":"Picachu"
}

###
DELETE  http://localhost:3000/pokemon/152