GET http://localhost:3000/pokemon

###
GET http://localhost:3000/pokemon/2

###
POST http://localhost:3000/pokemon
Content-Type: application/json

{
    "pokemon": "Mewtwo"
}

###
DELETE http://localhost:3000/pokemon/4